camera:
  vid: 1267
  pid: 3198
  frame_rate: QUARTER
  led_current: ULTRA_HIGH
  exposure_setting: DEFAULT
roi:
  enabled: false
  x1: 40
  y1: 40
  x2: 120
  y2: 120
thresholds:
  open: 25
  closed: 80
analysis:
  min_state_duration: 5
  history_size: 500
display:
  smoothing_window: 16
  show_raw_data: true
  enable_smoothing: true
